name: Update LLM Benchmark Data

on:
  schedule:
    # Runs at 08:00 UTC every day
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest

    steps:
      - name: Send Benchmark Requests
        run: |
          # Pre-warm any spun-down instances (only audio right now)
          curl -f -X POST "https://ai-benchmarks.fly.dev/bench?mode=audio&max_tokens=20&num_requests=1"
          # Run the benchmarks
          regions=("sea" "iad" "cdg")
          media=("text" "image" "audio")
          for region in "${regions[@]}"; do
            for medium in "${media[@]}"; do
              curl -f -X POST "https://ai-benchmarks.fly.dev/bench?mode=$medium&max_tokens=20&spread=30&store" -H "fly-prefer-region: $region"
            done
          done
