name: Update LLM Benchmark Data

on:
  schedule:
    # Runs at 08:00 UTC every day
    - cron: "0 8 * * *"
  workflow_dispatch:
    inputs:
      max_parallel:
        description: 'Maximum number of parallel jobs (1-20, use 1 for sequential execution)'
        required: true
        default: 10
        type: number

jobs:
  pre-warm:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-warm audio instance
        run: curl -f -X POST "https://ai-benchmarks.fly.dev/bench?mode=audio&max_tokens=20&num_requests=1"

  run-benchmarks:
    needs: pre-warm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [sea, iad, cdg, nrt]
        medium: [text, tools, image, audio]
      max-parallel: ${{ github.event.inputs.max_parallel || 10 }}
    
    steps:
      - name: Send Benchmark Request
        env:
          MAX_TOKENS: ${{ (matrix.medium == 'tools' && 100) || 20 }}
        run: |
          echo "Running benchmark for ${{ matrix.medium }} in region ${{ matrix.region }}"
          curl -f -X POST "https://ai-benchmarks.fly.dev/bench?mode=${{ matrix.medium }}&max_tokens=$MAX_TOKENS&spread=30&store" -H "fly-prefer-region: ${{ matrix.region }}"
          echo "Benchmark completed for ${{ matrix.medium }} in region ${{ matrix.region }}"
